#!/bin/sh
cachefile="$XDG_CACHE_HOME/.tmux-harpoon-sessions"

help() {
    echo
    echo "Usage:"
    echo "    ${0##*/} [options] [args]"
    echo "Options:"
    echo "    -a                    Track current tmux session"
    echo "    -r [session_name]     Stop tracking session with session name. If"
    echo "                          session_name is not passed then remove"
    echo "                          current session"
    echo "    -l                    List tracked sessions"
}

remove() {
    session_name="$1"
    sed -i "/^$session_name/d" "$cachefile"
}

view() {
    entry="$(sed "s/\(.*\)=\(.*\)/$(tput bold)\1$(tput sgr0) \2/;s|$HOME/||" "$cachefile" | align ' ')"
    name="$(echo "$entry" | cut -d ' ' -f 1)"
    path="$HOME/$(echo "$entry" | rev | cut -d ' ' -f 1 | rev)"
    _switch "$name" "$path"
}

add() {
    tmux display -p '#{session_name}=#{session_path}' >>"$cachefile"
    awk -i inplace '!seen[$0]++' "$cachefile" # de-duplicate
    cat "$cachefile"
}

_switch() {
    name="$1"
    path="$2"
    if ! { sessions_has_match "$name=$path"; }; then
        tmux new -ds "$name" -c "$path"
    fi
    tmux switch-client -t "$name"
}

switch() {
    index="$1"
    count=1
    while IFS='=' read -r name path; do
        if [ "$count" = "$index" ]; then
            _switch "$name" "$path"
        fi
        count=$((count + 1))
    done <"$cachefile"
}

sessions_has_match() {
    list_sessions | grep -wq "^$1="
}

list_sessions() {
    tmux ls -F '#{session_name}=#{session_path}'
}

bold() {
    printf "\033[1m%s\033[0m\n" "$*"
}

main() {
    while getopts ":harls" opt; do
        case "$opt" in
        h | :) help && exit 0 ;;
        a) add ;;
        r) remove "$OPTARG" ;;
        l) view ;;
        s) switch "$OPTARG" ;;
        \?) help && exit 1 ;;
        esac
    done
}

main "$@"
